;(function(window,document,undefined){var z,aa=aa||{};function ba(a,c,b){return a.call.apply(a.bind,arguments)}function ca(a,c,b){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,e);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function da(a,c,b){da=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return da.apply(null,arguments)}
var ea=aa.qb&&Date.now||function(){return+new Date};mti={bind:function(a,c,b){var e=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){e.push.apply(e,arguments);return c.apply(a,e)}}};var fa={};function ga(a,c){this.g=c||a;this.C=this.g.document;this.b=void 0}z=ga.prototype;z.createElement=function(a,c,b){a=this.C.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?ha(this,a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.C.createTextNode(b));return a};function C(a,c,b){a=a.C.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}z.Ta=function(a){function c(){b.C.body?a():setTimeout(c,0)}var b=this;c()};
function ia(a){a.parentNode&&a.parentNode.removeChild(a)}function E(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}
function ja(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}function ma(a,c){if("undefined"!==typeof SVGElement&&a instanceof SVGElement)return!1;for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return!0;return!1}
function ha(a,c,b){if(void 0===a.b){var e=a.C.createElement("p");e.innerHTML='<a style="top:1px;">w</a>';a.b=/top/.test(e.getElementsByTagName("a")[0].getAttribute("style"))}a.b?c.setAttribute("style",b):c.style.cssText=b}
z.getComputedStyle=function(a){if("undefined"!=typeof a&&null!=a){if(1!=a.nodeType)return"";var c={};if("undefined"!=typeof a.currentStyle&&null!=a.currentStyle)return c.fontFamily=a.currentStyle.fontFamily,c.fontWeight="normal"==a.currentStyle.fontWeight?400:"bold"==a.currentStyle.fontWeight?700:a.currentStyle.fontWeight,c.fontStyle=a.currentStyle.fontStyle,c;a=this.C.defaultView.getComputedStyle(a,null);if("undefined"!=typeof a&&null!=a)return c.fontFamily=a.getPropertyValue("font-family"),c.fontWeight=
"normal"==a.getPropertyValue("font-weight")?400:"bold"==a.getPropertyValue("font-weight")?700:a.getPropertyValue("font-weight"),c.fontStyle=a.getPropertyValue("font-style"),c}return""};z.G=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.C.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function na(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontWeight;var b=a.C.defaultView.getComputedStyle(c,null);if(b){var e=b.getPropertyValue("font-weight");return"bold"==e.toLowerCase()?700:"normal"==e.toLowerCase()?400:b.getPropertyValue("font-weight")}}return""}
function oa(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontStyle;var b=a.C.defaultView.getComputedStyle(c,null);if(b)return b.getPropertyValue("font-style")}return""}
function pa(a,c){var b="";if(void 0!=typeof c&&null!=c){void 0!=c&&null!=c&&"INPUT"==c.tagName&&(b+=c.value);c=c.childNodes||c;for(var e="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),d=0;d<c.length;d++)if(8!=c[d].nodeType&&0>a.indexOf(e,c[d].tagName?c[d].tagName.toLowerCase():"")){var f;f=(f=c[d].parentNode)?"undefined"!=typeof f.currentStyle?f.currentStyle.textTransform:(f=a.C.defaultView.getComputedStyle(f,null))?f.getPropertyValue("text-transform"):
"":void 0;if("none"!=f)f=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):"",b+=f.toLowerCase()+f.toUpperCase();else{if("none"!=qa(a,c[d].parentNode)){var h=c[d].parentNode;f=qa(a,c[d].parentNode);if("undefined"!=typeof h){for(var g=h.childNodes,k=h=0;k<g.length;k++)1==g[k].nodeType&&h++;g="";switch(f){case "upper-alpha":g="ABCDEFGHIJKLMNOPQRSTUVWXYZ".substring(0,h);break;case "lower-latin":g="abcdefghijklmnopqrstuvwxyz".substring(0,h);break;case "decimal":g="1234567890".substring(0,
h);break;case "decimal-leading-zero":g="0"+"1234567890".substring(0,h);break;case "lower-roman":g="ivxlcdm";break;case "upper-roman":g="IVXLCDM";break;default:g=""}}b=b+g}b+=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):""}}return b}}z.getElementById=function(a){return this.C.getElementById(a)};
function sa(a,c){if(document.getElementsByClassName)return document.getElementsByClassName(c);var b=[];ta(a.a,document.body,function(a){var d;d=a.className;var f;if(d)for(d=d.split(" "),f=0;f<d.length;f++)if(d[f]===c){b.push(a);break}});return b}
z.U=function(a,c,b){var e=[],d=this.G(a).split(","),f;a:if(f=!1,d instanceof Array)for(var h=0;h<d.length;h++)if(b instanceof Array)for(var g=0;g<b.length;g++){if(H(d[h])==H(b[g])){f=!0;break a}}else{if(H(d[h])==H(b)){f=!0;break}}else if(b instanceof Array)for(h=0;h<b.length;h++)if(d==b[h]){f=!0;break}if(f)return null;if(b instanceof Array)for(f=0;f<d.length;f++)if(H(d[f])!=c)if(-1<H(d[f]).indexOf(c))for(h=0;h<b.length;h++)""!=b[h]&&(e.push(b[h]),e.push(c));else e.push(d[f]);else if(b instanceof Array)for(h=
0;h<b.length;h++)""!=b[h]&&(e.push(b[h]),e.push(c));else e.push(b),e.push(c);else for(f=0;f<d.length;f++)H(d[f])!=c?-1<H(d[f]).indexOf(c)?(e.push(b),e.push(c)):e.push(d[f]):(e.push(b),e.push(c));e=ua(e);if(1<e.length&&e[0]!=c){b="";for(f=0;f<e.length;f++)b+="'"+e[f]+"'",f!=e.length-1&&(b+=",");b+="";a.setAttribute("data-mtiFont",c);c=""+b;a.style.setProperty?a.style.setProperty("font-family",""):a.style.setAttribute("font-family","");a.setAttribute("style",a.style.cssText+"font-family:"+c+" !important;")}else return null};
function va(a,c){for(var b=c.parentNode;null!=b;){if(b==a)return!0;b=b.parentNode}return!1}function ta(a,c,b){b(c);for(c=c.firstChild;c;)ta(a,c,b),c=c.nextSibling}function qa(a,c){if(c){if("undefined"!=typeof c.currentStyle)return c.currentStyle["list-style-type"];var b=a.C.defaultView.getComputedStyle(c,null);return b?b.getPropertyValue("list-style-type"):""}}z.indexOf=function(a,c){if(a){if(a.indexOf)return a.indexOf(c);for(var b=0;b<a.length;b++)if(a[b]==c)return b}return-1};
function H(a){return a.replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|")}function ua(a){for(var c={},b=[],e=0,d=a.length;e<d;++e)c.hasOwnProperty(H(a[e]))||(b.push(H(a[e])),c[H(a[e])]=1);return b}z.G=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.C.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function wa(a){if(a&&"string"==typeof a){var c="",b=a.length,e=null;if("from"in Array&&"Set"in window)c=Array.from(new Set(a)).join("");else for(var d=0;d<b;d++)e=a.charAt(d),-1==c.indexOf(e)&&(c+=e);return c}return""};function J(a,c){this.g=a;this.b=c};function L(a,c,b,e){this.i=null!=a?a:null;this.J=null!=c?c:null;this.b=null!=b?b:null;this.g=null!=e?e:null}var xa=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;L.prototype.toString=function(){return[this.i,this.J||"",this.b||"",this.g||""].join("")};
function M(a){a=xa.exec(a);var c=null,b=null,e=null,d=null;a&&(null!==a[1]&&a[1]&&(c=parseInt(a[1],10)),null!==a[2]&&a[2]&&(b=parseInt(a[2],10)),null!==a[3]&&a[3]&&(e=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?d=parseInt(a[4],10):d=a[4]));return new L(c,b,e,d)};function O(a,c,b,e,d,f,h,g){this.X=a;this.ka=c;this.Va=b;this.Ua=e;this.sa=d;this.eb=f;this.b=g}O.prototype.getName=function(){return this.X};function ya(){this.c=navigator.userAgent}var za=new O("Unknown",new L,"Unknown",new L,"Unknown",new L,0,new J(!1,!1));
function Aa(){var a=new ya;if(-1!=a.c.indexOf("MSIE")||-1!=a.c.indexOf("Trident/")){var c=Ba(a),b=M(Ca(a)),e=null,d=null,f=null,f=P(a.c,/Trident\/([\d\w\.]+)/,1),e=-1!=a.c.indexOf("MSIE")?M(P(a.c,/MSIE ([\d\w\.]+)/,1)):M(P(a.c,/rv:([\d\w\.]+)/,1));""!=f?(d="Trident",f=M(f)):(d="Unknown",f=new L);a=new O("MSIE",e,d,f,c,b,0,new J("Windows"==c&&6<=e.i||"Windows Phone"==c&&8<=b.i,!1))}else if(-1!=a.c.indexOf("Opera"))a:if(c="Unknown",b=M(P(a.c,/Presto\/([\d\w\.]+)/,1)),e=M(Ca(a)),null!==b.i?c="Presto":
(-1!=a.c.indexOf("Gecko")&&(c="Gecko"),b=M(P(a.c,/rv:([^\)]+)/,1))),-1!=a.c.indexOf("Opera Mini/"))d=M(P(a.c,/Opera Mini\/([\d\.]+)/,1)),a=new O("OperaMini",d,c,b,Ba(a),e,0,new J(!1,!1));else{if(-1!=a.c.indexOf("Version/")&&(d=M(P(a.c,/Version\/([\d\.]+)/,1)),null!==d.i)){a=new O("Opera",d,c,b,Ba(a),e,0,new J(10<=d.i,!1));break a}d=M(P(a.c,/Opera[\/ ]([\d\.]+)/,1));a=null!==d.i?new O("Opera",d,c,b,Ba(a),e,0,new J(10<=d.i,!1)):new O("Opera",new L,c,b,Ba(a),e,0,new J(!1,!1))}else/OPR\/[\d.]+/.test(a.c)?
a=Da(a):/AppleWeb(K|k)it/.test(a.c)?a=Da(a):-1!=a.c.indexOf("Gecko")?(c="Unknown",b=new L,e=M(Ca(a)),d=!1,-1!=a.c.indexOf("Firefox")?(c="Firefox",b=M(P(a.c,/Firefox\/([\d\w\.]+)/,1)),d=3<=b.i&&5<=b.J):-1!=a.c.indexOf("Mozilla")&&(c="Mozilla"),f=M(P(a.c,/rv:([^\)]+)/,1)),d||(d=1<f.i||1==f.i&&9<f.J||1==f.i&&9==f.J&&2<=f.b),a=new O(c,b,"Gecko",f,Ba(a),e,0,new J(d,!1))):a=za;return a}
function Ba(a){var c=P(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=P(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function Ca(a){var c=P(a.c,/Windows Phone( OS)? ([^;)]+)/,2);if(c||(c=P(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2))||(c=P(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;if(c=P(a.c,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var c=c.split(/\s/),b=0;b<c.length;b+=1)if(/^[\d\._]+$/.test(c[b]))return c[b];return(a=P(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function Da(a){var c=Ba(a),b=M(Ca(a)),e=M(P(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),d="Unknown",f=new L,f="Unknown",h=!1;/OPR\/[\d.]+/.test(a.c)?d="Opera":-1!=a.c.indexOf("Edge")?d="Edge":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(a.c)?d="Silk":"BlackBerry"==c||"Android"==c?d="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?d="PhantomJS":-1!=a.c.indexOf("Safari")?d="Safari":-1!=a.c.indexOf("AdobeAIR")?d="AdobeAIR":-1!=a.c.indexOf("PlayStation")?
d="BuiltinBrowser":-1!=a.c.indexOf("FBAN")&&(d="FBWebUI");"BuiltinBrowser"==d?f="Unknown":"Silk"==d?f=P(a.c,/Silk\/([\d\._]+)/,1):"Chrome"==d?f=P(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?f=P(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==d?f=P(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==d?f=P(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==d?f=P(a.c,/PhantomJS\/([\d.]+)/,1):"FBWebUI"==d?f=P(a.c,/FBSV\/([\d.]+)/,1):"Edge"==d&&(f=P(a.c,/Edge\/([\d.]+)/,1));f=M(f);h="AdobeAIR"==d?2<f.i||2==f.i&&
5<=f.J:"BlackBerry"==c?10<=b.i:"Android"==c?2<b.i||2==b.i&&1<b.J:526<=e.i||525<=e.i&&13<=e.J;return new O(d,f,"AppleWebKit",e,c,b,0,new J(h,536>e.i||536==e.i&&11>e.J))}function P(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""};function Ea(a){this.g=a||"-"}Ea.prototype.b=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.g)};function Fa(a,c,b){this.a=a;this.g=c;this.s=b;this.b=new Ea("-")}function Ga(a){E(a.g,a.b.b("mti","loading"));Ha(a,"loading")}function Ia(a){ja(a.g,a.b.b("mti","loading"));ma(a.g,a.b.b("mti","active"))||E(a.g,a.b.b("mti","inactive"));Ha(a,"inactive")}function Ha(a,c,b){if(a.s[c])if(b)a.s[c](b.getName(),Q(b));else a.s[c]()};function R(a,c){this.X=a;this.ca=4;this.$="n";var b=(c||"n4").match(/^([nio])([1-9])$/i);b&&(this.$=b[1],this.ca=parseInt(b[2],10))}R.prototype.getName=function(){return this.X};R.prototype.Sa=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push("'"+e+"'")}return c.join(",")};function Q(a){return a.$+a.ca};function Ja(a,c){this.a=a;this.g=c;this.b=this.a.createElement("span",{"aria-hidden":"true"},this.g)}function Ka(a){C(a.a,"body",a.b)}function La(a){var c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.Sa(a.X)+"!important;",b="normal",e=a.ca+"00";"o"===a.$?b="oblique":"i"===a.$&&(b="italic");return c+("font-style:"+b+";font-weight:"+e+";")};function Ma(a,c,b,e,d,f,h,g){this.na=a;this.$a=c;this.a=b;this.b=e;this.ga=g||"BESb\uc5d0swy";this.ra=d;this.N={};this.cb=f||5E4;this.pa=h||null;this.s=this.g=null;a=new Ja(this.a,this.ga);Ka(a);for(var k in S)S.hasOwnProperty(k)&&(c=new R(S[k],Q(this.b)),ha(a.a,a.b,La(c)),this.N[S[k]]=a.b.offsetWidth);ia(a.b)}var S={pb:"serif",ob:"sans-serif",mb:"monospace"};function Na(a,c,b){for(var e in S)if(S.hasOwnProperty(e)&&c===a.N[S[e]]&&b===a.N[S[e]])return!0;return!1}
function Oa(a){var c=a.g.b.offsetWidth,b=a.s.b.offsetWidth;c===a.N.serif&&b===a.N["sans-serif"]||a.ra.b&&Na(a,c,b)?ea()-a.ab>=a.cb?a.ra.b&&Na(a,c,b)&&(null===a.pa||a.pa.hasOwnProperty(a.b.getName()))?Pa(a,a.na):Pa(a,a.$a):Qa(a):Pa(a,a.na)}function Qa(a){setTimeout(da(function(){Oa(this)},a),25)}function Pa(a,c){ia(a.g.b);ia(a.s.b);c(a.b)};function Ra(a,c,b,e){this.a=c;this.b=b;this.g=0;this.N=this.s=!1;this.ra=e;this.pa=a.b}
function Sa(a,c,b,e,d){if(0===c.length&&d)Ia(a.b);else for(a.g+=c.length,d&&(a.s=d),d=0;d<c.length;d++){var f=c[d],h=b[f.getName()],g=a.b,k=f;E(g.g,g.b.b("mti",k.getName(),Q(k).toString(),"loading"));Ha(g,"fontloading",k);f=new Ma(da(a.ga,a),da(a.na,a),a.a,f,a.pa,a.ra,e,h);f.g=new Ja(f.a,f.ga);Ka(f.g);f.s=new Ja(f.a,f.ga);Ka(f.s);f.ab=ea();h=f.g;g=new R(f.b.getName()+",serif",Q(f.b));ha(h.a,h.b,La(g));h=f.s;g=new R(f.b.getName()+",sans-serif",Q(f.b));ha(h.a,h.b,La(g));Oa(f)}}
Ra.prototype.ga=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"loading"));ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"inactive"));E(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"active"));Ha(c,"fontactive",a);this.N=!0;Ta(this)};Ra.prototype.na=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"loading"));ma(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"active"))||E(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"inactive"));Ha(c,"fontinactive",a);Ta(this)};
function Ta(a){0==--a.g&&a.s&&(a.N?(a=a.b,ja(a.g,a.b.b("mti","loading")),ja(a.g,a.b.b("mti","inactive")),E(a.g,a.b.b("mti","active")),Ha(a,"active")):Ia(a.b))};mti.kb=function(){this.Sa='"'};mti.H=function(){this.ta=mti.H.g;this.P=mti.H.s};mti.H.g=["font-style","font-weight"];mti.H.s={"font-style":[["n","normal"]],"font-weight":[["4","normal"]]};mti.H.b=function(a,c,b){this.Oa=a;this.gb=c;this.P=b};mti.H.b.prototype.compact=function(a,c){for(var b=0;b<this.P.length;b++)if(c==this.P[b][1]){a[this.Oa]=this.P[b][0];break}};mti.H.b.prototype.expand=function(a,c){for(var b=0;b<this.P.length;b++)if(c==this.P[b][0]){a[this.Oa]=this.gb+":"+this.P[b][1];break}};
mti.H.prototype.compact=function(a){var c=["n","4"];a=a.split(";");for(var b=0,e=a.length;b<e;b++){var d=a[b].replace(/\s+/g,"").split(":");if(2==d.length){var f=d[1];a:{for(var d=d[0],h=0;h<this.ta.length;h++)if(d==this.ta[h]){d=new mti.H.b(h,d,this.P[d]);break a}d=null}d&&d.compact(c,f)}}return c.join("")};
mti.H.prototype.expand=function(a){if(2!=a.length)return null;for(var c=[null,null],b=0,e=this.ta.length;b<e;b++){var d=this.ta[b];(new mti.H.b(b,d,this.P[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":null};function Ua(a,c,b){this.s=a;this.Ka=c;this.c=b;this.b=this.g=0}Ua.prototype.load=function(a){var c=a.context||this.s;this.a=new ga(this.s,c);c=new Fa(this.a,c.document.documentElement,a);if(this.c.b.g){var b=this.Ka,e=this.a,d=[],f;for(f in a)if(a.hasOwnProperty(f)){var h=b.b[f];h&&d.push(h(a[f],e))}a=a.timeout;this.b=this.g=d.length;a=new Ra(this.c,this.a,c,a);f=0;for(b=d.length;f<b;f++)e=d[f],e.jb(this.c,da(this.N,this,e,c,a))}else Ia(c)};
Ua.prototype.N=function(a,c,b,e){var d=this;e?a.load(function(a,e,g){Va(d,c,b,a,e,g)}):(a=0==--this.g,this.b--,a&&(0==this.b?Ia(c):Ga(c)),Sa(b,[],{},null,a))};function Va(a,c,b,e,d,f){var h=0==--a.g;h&&Ga(c);setTimeout(function(){Sa(b,e,d||{},f||null,h)},0)};var Wa=window,Xa=Aa(),Ya=Wa.MonoTypeWebFonts=new Ua(window,new function(){this.b={}},Xa);window.MonoTypeWebFonts.load=Ya.load;mti.Ca=4E4;
mti.o=function(a,c,b,e,d){this.R=a;this.c=c;this.a=b;this.f=e;this.Wa={};this.l=d;this.h=[];this.v=e.efg;this.m={};this.j=e.efg;this.R.mti_element_cache=[];this.oa=[];this.ua=[];this.D=[];this.fa={};this.W=[];this.Z=[];this.va=0;this.version=this.K=void 0;this.Ia={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};this.w={};this.Pa=0;1==T.UseTextIndent?this.ja="text-align:left;text-indent:-9999px;font-size:0px":this.ja="visibility:hidden;";this.ma=this.f.reqSub||(void 0!==
T.EnableDSForAllFonts?T.EnableDSForAllFonts:!1);this.K=a=this.c.getName().toLowerCase();this.version=this.c.ka;this.Ya="edge"==a?!0:!1;this.xa={EOT:2,SVG:11,OTF:13,TTF:1,WOFF:3,WOFF2:14}};mti.o.g="monotype";mti.o.b=!1;mti.o.prototype={jb:function(a,c){var b=this,e=b.f.projectId,d;if(e){b.R.mti_element_cache=[];Za(b);if(null!==b.l&&!1===b.ma)if(setTimeout(function(){document.documentElement.style.visibility=""},300),void 0!==T.PreLoadFonts&&b.isArray(T.PreLoadFonts)){var f=T.PreLoadFonts;d=[];for(var h=0;h<f.length;h++){var g=f[h].split(":"),k=g[0],g=1<g.length?g[1].split(","):"n4",l="n4";if(b.isArray(g)&&0<g.length)for(var m=0;m<g.length;m++)l=g[m],l=b.Na(k,l),void 0!==l&&d.push(l);else l=b.Na(k,l),void 0!==l&&
d.push(l)}$a(b,d,"","",!0);c(!0)}else b.la.call(b,!0,!0,!0),void 0===T.LoadAllFonts&&void 0===T.EnableCustomFOUTHandler||c(T.LoadAllFonts||T.EnableCustomFOUTHandler),b.za();else T.UseHybrid&&(setTimeout(function(){document.documentElement.style.visibility=""},700),T.EnableCustomFOUTHandler=!0,b.ba(b.f.pfL,!1,!0)),d=function(){T.UseHybrid&&(window.MonoTypeWebFonts.addEvent("active",function(){ab(b,b.ba,!1)}),window.MonoTypeWebFonts.addEvent("inactive",function(){ab(b,b.ba,!1)}));b.za();b.ma?b.la.call(b):
b.la.call(b,!0);c(T.EnableCustomFOUTHandler)},!0===T.isAsync?T.onReady=d:(b.ma?bb(b,d):this.Ta(function(){b.la.call(b,!0);c(T.EnableCustomFOUTHandler)}),b.f.enableOtf&&!b.ma&&bb(b,b.za.bind(b)));setTimeout(function(){document.documentElement.style.visibility=""},700);d=null;"function"===typeof b.R["__MonotypeConfiguration__"+e]&&(d=b.R["__MonotypeConfiguration__"+e]());if(void 0!==d||null!==d)loadAllFonts=d.loadAllFonts;var q=function(){var a=[];if(loadAllFonts)for(var c=0;c<b.f.pfL.length;c++){var d=
"n4",f=400,h="normal";void 0!=b.f.pfL[c].fontWeight&&void 0!=b.f.pfL[c].fontStyle&&(h=b.f.pfL[c].fontStyle,f=b.f.pfL[c].fontWeight,d=h.charAt(0)+f/100);var g=b.f.pfL[c].fontfamily,d=new R(g,d);d.fontfamily=g;d.fontWeight=f;d.fontStyle=h;a.push(d)}if(0<b.h.length||0<a.length){var k=[];b.h&&(k=b.h);loadAllFonts&&(k=a);b.R["__mti_fntLst"+e]=function(){for(var a=[],c=[],b=0;b<k.length;b++)a.push({fontfamily:k[b].X,fontStyle:k[b].$,fontWeight:k[b].ca}),c.push(k[b]);return a}}else setTimeout(function(){q()},
0)};q()}else c(T.EnableCustomFOUTHandler)},la:function(a,c,b){a=this;var e=!1,d={},f={};T.UseHybrid&&0<a.va?a.W.length!=a.va&&(e=!0):e=!0;if(e||null!=a.l){var f=new V(document.body,a.a,a.f.pfL),h=f.O(document.body),d=f.ha(),f=f.F;null!=a.l&&mti.bind(a.l,a.l.load,f)();if(c)"";else{c=a;for(var e=f,g=0;g<e.length;g++)for(var k in c.m)-1<c.a.G(e[g]).indexOf(k)&&(void 0==e[g].getAttribute("id"),c.a.U(e[g],k,c.m[k],c.tb,c.v))}}k=[];for(c=0;c<a.f.pfL.length;c++){var e=a.f.pfL[c],l,m,q,g=e.enableSubsetting,
r=e.enableOtf,u=e.contentIds,v=e.subsetOption;if(!e.enableSubsetting){void 0!=e.fontWeight&&void 0!=e.fontStyle&&(m=e.fontWeight,q=e.fontStyle,l=q.charAt(0)+m/100);var n=new R(e.fontfamily,l);n.fontfamily=e.fontfamily;n.fontWeight=void 0!=e.fontWeight?m:"4";n.fontStyle=void 0!=e.fontStyle?q:"n";n.enableSubsetting=g;n.contentIds=u;n.enableOtf=r;n.subsetOption=v;k.push(n);b&&d.push(n)}}l=k;m=null==l?0:l.length;q={};c=[];for(k=0;k<m;k+=1)q[l[k].X+"||"+l[k].ca+"||"+l[k].$]=l[k];for(k in q)c.push(q[k]);
k=c;$a(a,d,h,"",!0);b||$a(a,k,h,"",!1);a.R.mti_element_cache=f},Na:function(a,c){for(var b=0;b<this.f.pfL.length;b++){var e=this.f.pfL[b],d,f,h;void 0!=e.fontWeight&&void 0!=e.fontStyle&&(f=e.fontWeight,h=e.fontStyle,d=h.charAt(0)+f/100);if(e.fontfamily==a&&(this.j?c==d:1)){var b=e.enableSubsetting,g=e.enableOtf,k=e.contentIds,l=e.subsetOption,m=e.variationId,q=e.otfJsContentId;d=new R(e.fontfamily,d);d.fontfamily=e.fontfamily;d.fontWeight=void 0!=e.fontWeight?f:"4";d.fontStyle=void 0!=e.fontStyle?
h:"n";d.enableSubsetting=b;d.contentIds=k;d.enableOtf=g;d.subsetOption=l;d.variationId=m;d.otfJsContentId=q;return d}}}};MonoTypeWebFonts.Ka.b[mti.o.g]=function(a){var c=Aa(),b=new ga(window),e=null;a.enableOtf&&(e=new mti.da(b,c,a));c=new mti.o(window,c,b,a,e);if(a.reqSub||T.EnableDSForAllFonts||a.enableOtf){var d=new mti.Fa(c);window.MonoTypeWebFonts.renderPartial=function(a,b){d.hb(a,b)}}return c};
var cb={ec:"true",dfcURL:"http://api2.fonts.com/FontSubsetter.ashx",fontdataversion:"v2",sO:"true",ffArray:{safari:{"3.1":"ttf","5.1":"woff"},msafari:{1:"svg","4.2":"ttf","5.1":"woff","10.0":"woff2"},chrome:{3:"svg",4:"ttf",5:"woff",36:"woff2"},opera:{10:"ttf","11.10":"woff","26.0":"woff2"},msie:{4:"eot",9:"woff"},mozilla:{"3.5":"ttf","3.6":"woff","39.0":"woff2"},edge:{12:"woff",14:"woff2"}},bsmcArray:{safari:{"3.1":"2000","5.0":"15600"},msafari:{1:"15600"},chrome:{3:"15600"},opera:{10:"15600"},msie:{4:"1000",
9:"2080"},mozilla:{"3.5":"15600"},edge:{12:"15600"}},fctypeArray:{ttf:"1",eot:"2",woff:"3",svg:"11",otf:"13",woff2:"14"},specialChar:"%u201C %u201D %u2200 %u2202 %u2203 %u2205 %u2207 %u2208 %u2209 %u220B %u220F %u2211 %u2018 %u2019 %B0 %u2026 %u2122 %A9 %AE %u2014 %u2013 %A7 %B1 %B7 %u2032 %u2033 %u20AC %u2248 %u2260 %u2264 %u2265 %u221A %u221D %u2220 %u2225 %u2227 %u2228 %u2229 %u222A %u222B %u222E %u2234 %u2235 %u2236 %u2237 %u223D %u224C %u2261 %u226E %u226F %u2299 %u22A5 %u0391 %u0392 %u0393 %u0394 %u0395 %u0396 %u0397 %u0398 %u0399 %u039A %u039B %u039C %u039D %u039E %u039F %u03A0 %u03A1 %u03A3 %u03A4 %u03A5 %u03A6 %u03A7 %u03A8 %u03A9 %u221E %u2190 %u2191 %u2192 %u2193 %u2640 %u2642 + %22 %5C %23 %26 %3F %B7 %3B %3A".split(" ")};
function W(a,c){return void 0!=cb[c]?cb[c]:a.f[c]};function $a(a,c,b,e,d){var f,h="TTF",g=a.f.projectId,k=W(a,"ec"),l=a.f.fcURL,m=W(a,"dfcURL"),q=document.getElementById("mti_fontface_"+a.f.projectId);null===q&&(q=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+a.f.projectId}));var r="",u=!1,v={},n={};a.m={};var p=null,w=null;void 0!=T.CustomDfcURL&&(m=T.CustomDfcURL);c||(c=[]);for(var t=0;t<c.length;t++){var y=c[t],x=c[t].fontfamily,B=c[t].contentIds,A=c[t].enableOtf,F=y.subsetOption;f=null;a.j&&(p=c[t].fontWeight,w=c[t].fontStyle,
f=w.charAt(0)+p/100,a.v=!0);d&&(null==f?new R(x):new R(x,f),a.h.push(c[t]));26<x.length&&!a.w&&(a.w[x+"_"+(null==f?"n4":f)]="mtiFont"+a.Pa++);var h=a.aa(B),G="";a.j?G=x+"_"+w.charAt(0)+p/100:G=x+"_n4";y=1==T.EnableDSForAllFonts?!0:y.enableSubsetting;var n=a,K=x,D=p,U=w,I=e,N=n.c.getName(),N=N.toLowerCase();f=n.c.ka;"mozilla"==N.toLowerCase()&&"Unknown"==f&&(N="msie");f="?";k&&(f+=a.f.ck+"&");f+="fctypeId="+W(n,"fctypeArray")[h]+"&fcId="+B.TTF;f+="&projectId="+g;f+="&content=";var ra="";if(b){var ka=
null,la=db(b,K,D,U);la?"":la="";var Z=la.split("::"),la=Z[0],Z=Z[1],K=I?K+I:K;n.v&&(K+="_"+U.charAt(0)+D/100);D=la.split("").sort().join("");D=gb(n,D,K,I);ka="";la&&(ka=D.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&",""));if(ka&&0<ka.length||Z&&0<Z.length)ra+=("msie"==N?ka||"":encodeURIComponent(ka||""))+"BESb\uc5d0swyMm",void 0!==Z&&""!=Z&&(ra+=Z)}I=f+ra;N=W(n,"bsmcArray");D=n.K;"firefox"==D&&(D="mozilla");/ipad|ipod|iphone/.test(n.c.sa.toLowerCase())&&(n.K="msafari");
n=n.version.i;N=N[D];D="";U=void 0;for(U in N)parseFloat(n)>=parseFloat(U)&&(D=N[U]);n=D;f=I.length>n?Math.ceil(I.length/(n-f.length)):1;N=f;D="";if(1<N||e){if(null!==b){u=!0;v[G]||(v[G]=[]);if(b)var eb=b[G];if(eb){n=[];I="";f="n4";a.j&&(f=w.charAt(0)+p/100);D=I=(a.w[x+"_"+f]?a.w[x+"_"+f]:x)+(e?e:"");D+="_"+f;v[G].push(D);b[D]=eb;if(D=1<N?hb(a,B,g,!1,l,m,a.f.ck,I,p,w,b,h,A,e):hb(a,B,g,y,l,m,a.f.ck,I,p,w,b,h,A,e,F))A="",A=I,r=ib(a,A,"",r,p,w,A,D,h,B,!0,"",!1,!0,e,fb,!1),n.push("'"+I+"'"),a.Z[x+"_"+
f]=I;a.m[x+(a.j?"_"+f:"")]=n}}}else if(D=hb(a,B,g,y,l,m,a.f.ck,x+(e?e:""),p,w,b,h,A,e,!1,F)){var fb="";(new V).qa(F)&&(h=jb(a));r=ib(a,x,"",r,p,w,x,D,h,B,!0,"",!1,!0,e,fb,!1)}}if(!0===u||e)e?Za(a,v,e):Za(a,v);""!=r&&C(a.a,"head",q);q.styleSheet?""==q.styleSheet.cssText?q.styleSheet.cssText=r:q.styleSheet.cssText=q.styleSheet.cssText+"\n"+r:q.appendChild(document.createTextNode(r))}
function hb(a,c,b,e,d,f,h,g,k,l,m,q,r,u,v,n){function p(n,m){var p=a.f.env;d=d.replace("http://","").replace("https://","");f=f.replace("http://","").replace("https://","");d="https://"+d+(r?"ot/":"");f="https://"+f;if(m.qa(n))if(t=f+"?",t+=h+"&",t+="fctypeId="+("15"==W(a,"fctypeArray")[jb(a)]?"3":W(a,"fctypeArray")[jb(a)])+"&fcId="+c.TTF,t+="&env="+p+"&projectId="+b,void 0!=n){var p=n.unicode,y=n.text,I=n.lang,x=n.ot;void 0!=p&&(t+="&ranges="+p);void 0!=y&&(t+="&content="+y.replace('"',"%22").replace("'",
"%27").replace("#","%23").replace("?","%3F").replace("&","%26"));void 0!=I&&(t+="&languages="+I);void 0!=x&&(t+="&ot="+x)}else t="";else e?(t=f+"?",t+=h+"&",t+="fctypeId="+("15"==W(a,"fctypeArray")[q]?"3":W(a,"fctypeArray")[q])+"&fcId="+c.TTF,11==q&&(t+="&origId="+w),void 0!==p&&""!=p&&(t+="&env="+p)):(""!==a.xa[q.toUpperCase()]?d+=a.xa[q.toUpperCase()]+"/":d+=a.xa.WOFF+"/",t=d+w+"."+q.toLowerCase()+"?"+h,a.j?A=l.charAt(0)+k/100:A="n4",p=g+"_"+A,-1<a.a.indexOf(a.W,p)&&(t=""),0>a.a.indexOf(a.W,p)&&
!v&&!r&&!u&&a.W.push(p)),""!=t&&(t+="&projectId="+b,null!=q&&"SVG"==q.toUpperCase()&&(t+="#"+w));return t}var w=c[q.toUpperCase()],t,y,x,B,A,F;T.UseHybrid&&(F=X(g),a.j?(A=l.charAt(0)+k/100,F=X(g,A)):A="n4",1==e&&kb(F)&&(e=!1));F=new V;if(F.qa(n))t=p(n,F);else if(e||T.EnableDSForAllFonts){if(m){m=db(m,g,k,l);if(null==m)return t="";if(m){B=m.split("").sort().join("");m=g;a.v&&(m+="_"+l.charAt(0)+k/100);B=gb(a,B,m,u);u&&(a.v?m=m.substring(0,m.length-8)+"_"+l.charAt(0)+k/100:m=m.substring(0,m.length-
5)+"_n4",a.fa[m]=B);B=lb(a,B).split("::");m=B[0];B=B[1].replace(":","");m&&(x=m.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&","").replace("%","%25"));if(x&&0<x.length||B&&0<B.length)y="&content="+(a.Ya?encodeURIComponent(x||""):x||"")+"BESb\uc5d0swyMm",""!=B&&(y+=B);t=p(n,F)+y}else return}}else p(n,F);return t}
mti.o.prototype.ba=function(a,c,b){if(!(null!=a&&1>a.length)){var e=this.f.projectId,d=this.f.fcURL,f=this.f.ck,h="",g,k,l="msie"==this.c.getName()?!0:!1,m=!1,q={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"},r=[];a=b?a:this.h;for(var u=0,v="n4",n=0;n<this.f.pfL.length;n++){var p=this.f.pfL[n],w=!1,t=p.fontfamily;p.enableSubsetting&&this.va++;if(b)w=!0;else for(u=0;u<a.length;u++)if(a[u].fontfamily==t&&(p.enableSubsetting||T.EnableDSForAllFonts)){if(this.v)a[u].fontWeight==
p.fontWeight&&a[u].fontStyle==p.fontStyle&&(w=!0,g=p.fontWeight,k=p.fontStyle,v=k.charAt(0)+g/100,y=X(t,v));else var y=X(t),w=!0;if(w){a.splice(u,1);break}}w&&(y=X(t),p.enableSubsetting||T.EnableDSForAllFonts)&&((void 0!=p.fontWeight&&void 0!=p.fontStyle&&(g=p.fontWeight,k=p.fontStyle,v=k.charAt(0)+g/100,y=X(t,v)),r.push(y),contentIdArray=p.contentIds,enableOtf=p.enableOtf,kb(y)||b)?kb(y)&&b&&(this.h.push(new R(t,v)),fFormat=this.aa(contentIdArray),fontURL=hb(this,contentIdArray,e,!1,d,"",f,t,g,k,
null,fFormat,enableOtf,!1,!1),""!=fontURL&&(this.oa.push(y),h=ib(this,t,"",h,g,k,t,fontURL,fFormat,contentIdArray,!0,"",!1,!0,!1,"",!1))):(m=!0,0>this.a.indexOf(this.oa,y)&&(fFormat=this.aa(contentIdArray),fontURL=hb(this,contentIdArray,e,!1,d,"",f,t,g,k,null,fFormat,enableOtf,!1,!0),""!=fontURL&&(this.oa.push(y),h+='@font-face{\nfont-family:"'+y+'";',h+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(p=q[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||
(p=q.TTF),h+=" format('"+p+"')"),h+=";}\n"))))}""!=h&&(b=this.a.getElementById("mti_fontface_"+e),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+this.f.projectId}),""!=h&&C(this.a,"head",b)),b.styleSheet?""!=b.styleSheet.cssText?(l=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==l&&(l=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=h&&C(this.a,"head",
l)),l.styleSheet.cssText=h):b.styleSheet.cssText=h:l?(l=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==l&&(l=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=h&&C(this.a,"head",l)),l.innerHTML+=h):b.innerHTML+=h);if(m){c=[];for(h=0;h<r.length;h++)c.push(new R(r[h]));Sa(new Ra(this.c,this.a,new Fa(this.a,document.documentElement,{fontactive:function(a){if("_f"==a.substr(a.length-2)&&
!kb(a)){var b=new Date;a=a.replace(/\s+/g,"%20");b.setDate(b.getDate()+1);document.cookie=a+"="+("1; expires="+b.toUTCString())}}}),6E5),c,{},{},!1)}}};var T=window.MTIConfig||{sb:!1,lb:!1,nb:!1};function V(a,c,b,e){this.ib=a;this.a=c;this.fb=b;this.Y={};this.F=[];this.h=[];e?this.Za=e:!1;this.Xa="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ")}
V.prototype=function(){function a(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text?c=!0:void 0!=typeof a.ot&&null!=a.ot&&""!=a.ot&&(c=!0));return c}function c(a,e,d){if(void 0!==a&&null!==a&&""!==a&&a.tagName&&1===a.nodeType)for(0>d.a.indexOf(d.Xa,a.tagName.toLowerCase())&&(e?d.Ma(a,e):d.Ma(a)),a=a.firstChild;a;)c(a,e,d),a=a.nextSibling}return{Ma:function(c,
e){var d=this.fb,f=this.a.getComputedStyle(c),h=f.fontFamily,g="",k=f.fontStyle,l=0,m=0,q="",h=(h||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=h)for(var h=h.split("|"),r="",l=0;l<h.length;l++)for(m=0;m<d.length;m++){var u=d[m],r=u.fontfamily,v,n,p=u.enableSubsetting,w=u.enableOtf,t=u.contentIds,y=u.subsetOption,x=!1,B=new RegExp("^("+h[l]+")$","ig");if(void 0!=u.fontWeight&&void 0!=u.fontStyle)v=u.fontWeight,n=u.fontStyle,q=n.charAt(0)+v/100,g="normal"==f.fontWeight?
400:"bold"==f.fontWeight?700:f.fontWeight;else{var A="h1 h2 h3 h4 h5 h6 strong b".split(" ");1==c.nodeType&&(g=0<=this.a.indexOf(A,c.tagName.toLowerCase())?400:"normal"==f.fontWeight?400:"bold"==f.fontWeight?700:400)}A=r.replace(/^\s|\s$/g,"");B.test(A)&&(void 0!=v||void 0!=n?g==v&&k==n&&(x=new R(A,q),x.fontfamily=A,x.fontWeight=v,x.fontStyle=n,x.enableSubsetting=p,x.contentIds=t,x.enableOtf=w,x.subsetOption=y,this.h.push(x),this.F.push(c),x=!0):(q="n4",x=new R(A),x.fontfamily=A,x.fontWeight=g/100,
x.fontStyle=k.charAt(0),x.enableSubsetting=p,x.contentIds=t,x.enableOtf=w,x.subsetOption=y,this.h.push(x),this.F.push(c),x=!0),x&&(1==T.EnableCustomFOUTHandler&&E(c,e?"mti_font_element"+e:"mti_font_element"),p=c.getAttribute("style"),(p=null!=p?"string"==typeof p?p:"cssText"in p?p.cssText:"":"")&&-1<this.a.indexOf(p,"font-weight")&&-1<this.a.indexOf(p,"font-style")?r+="_"+k.charAt(0)+g/100:r+=1<q.length?"_"+q:"",!u.enableSubsetting&&!T.EnableDSForAllFonts||a(y)||(u="",u=pa(this.a,c),this.Y[r.replace(/^\s|\s$/g,
"")]&&(u+=this.Y[r.replace(/^\s|\s$/g,"")]),this.Y[r.replace(/^\s|\s$/g,"")]=u)))}},O:function(a,e){c(this.ib,e,this);var d=!1,f;for(f in this.Y)if(d=!0,this.Za)break;else this.Y[f]=wa(this.Y[f]);return d?this.Y:null},ha:function(){var a=this.h,c=null==a?0:a.length,d={},f,h=[];for(f=0;f<c;f+=1)d[a[f].X+"||"+a[f].ca+"||"+a[f].$]=a[f];for(f in d)h.push(d[f]);return this.h=h},rb:function(){return this.F},qa:a}}();z=mti.o.prototype;z.load=function(a){a(this.h,this.Wa)};
function Za(a,c,b){var e=new Ea("-"),d=a.a.createElement("style",{type:"text/css",id:"mti_stylesheet_"+(b?"Aj_":"")+a.f.projectId}),f="";if(1==T.EnableCustomFOUTHandler||1==T.UseHybrid){for(var h=a.f.pfL,f=f+(".mti-loading .mti_font_element"+(b?"_Aj":"")+"{"+a.ja+"}\n"),g=0;g<h.length;g++){var k=h[g].fontfamily,l="4",m="n";a.j&&(l=h[g].fontWeight/100,m=h[g].fontStyle.charAt(0));b&&(k=k+b);k&&(f+="."+e.b("mti",k,m+l,"loading")+" .mti_font_element"+(b?b:"")+"{"+a.ja+"}\n")}f+=".mti_hide_element{"+a.ja+
"}"}for(g in a.f.selectorFontMap)if(e=a.f.selectorFontMap[g],k=e.familyName,a.j?(m=e.fontStyle,l=e.fontWeight):(m="normal",l="400"),c&&c[k]&&0<c[k].length&&(k=c[k].join("','")),b||(f=ib(a,k,g,f,l,m,"","","","",!1,e,!0)),1==T.EnableCustomFOUTHandler)for(m in f+="/*fout specific code:*/\n",l=g.split(","),m=void 0,l)f+=".mti-loading "+l[m]+"{"+a.ja+"}\n";""!=f&&C(a.a,"head",d);d.styleSheet?d.styleSheet.cssText=f:d.appendChild(document.createTextNode(f))}
function ib(a,c,b,e,d,f,h,g,k,l,m,q,r,u,v,n,p){1<a.a.indexOf(h,v)?v="":"";u?e+='@font-face{\nfont-family:"'+h+(v?v:"")+(n?n:"")+'";':"";u?"":e+=b+"{font-family:'"+c+"';";a.j&&!p&&(e=e+("\n font-style:"+f+";")+("\n font-weight:"+d+";"));g?e+='\nsrc:url("'+g+'")':"";m?(c=e,null!=k&&"EOT"==k.toUpperCase()||"MTX"==k.toUpperCase()||(b=a.Ia[k.toUpperCase()],l[k.toUpperCase()]||(b=a.Ia.TTF),c+=" format('"+b+"')"),e=c):"";if(r){k=e;if(null!=a.l&&(a=q.otf,l=q.vrnt,a&&null!=a&&""!=a)){q=a.split(" ");a=null;
if(void 0!=l)a=l.split(" ");else for(a=Array(q.length),l=0;l<a.length;++l)a[l]=1;if(0<q.length){r="-moz-font-feature-settings : '";c="-moz-font-feature-settings : ";b="-webkit-font-feature-settings : ";e="-ms-font-feature-settings : '";d="font-feature-settings : ";f="-o-font-feature-settings : ";h=!1;for(l=0;l<q.length;l++)g=q[l],m=a[l],"calt"==g&&(h=!0),b+='"'+g+'" '+m,d+='"'+g+'" '+m,f+='"'+g+'" '+m,r+=g+"= "+m,c+='"'+g+'" '+m,e+=g+"= "+m,l!=q.length-1?(e+=",",b+=",",r+=",",c+=",",f+=",",d+=","):
h?(f+=";",d+=";",b+=";",r+="';",c+=";",e+="';"):(f+=',"calt" 0;',d+=',"calt" 0;',b+=',"calt" 0;',r+="','calt=0';",c+=',"calt" 0;',e+="','calt=0';",h=!1);q="\n"+r+"\n"+c+"\n"+b+"\n"+e+"\n"+f+"\n"+d}else q="";k+=q}e=k}else"";return e+=";}\n"}z.Ta=function(a){function c(){document.body?a():setTimeout(c,0)}c()};
z.aa=function(a){var c=W(this,"ffArray"),b=this.K,e=this.version.i+this.version.J/10;"firefox"==this.K&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.sa.toLowerCase())&&(b="msafari",e=this.c.eb.i);var c=c[b],b="",d;for(d in c)parseFloat(e)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);""===b&&(b="ttf");return b};
function jb(a){var c=W(a,"ffArray"),b=a.K,e=a.version.i+a.version.J/10;"firefox"==a.K&&(b="mozilla");/ipad|ipod|iphone/.test(a.c.sa.toLowerCase())&&(b="msafari");a=c[b];var c="",d;for(d in a)parseFloat(e)>=parseFloat(d)&&(c=a[d]);""===c&&(c="ttf");return c}z.qa=function(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(c=!0));return c};
z.isArray=function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)};function X(a,c){void 0===c&&(c="n4");return a+"_"+c+"_f"}function mb(a,c){for(var b in c)if(a==c[b])return b;return!1};mti.o.prototype.aa=function(a){var c=W(this,"ffArray"),b=this.K,e=this.version.i+this.version.J/10;"firefox"==this.K&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.sa.toLowerCase())&&(b="msafari");var c=c[b],b="",d;for(d in c)parseFloat(e)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);return b};function nb(){for(var a="",c=0;5>c;c++)a+="abcdefghijklmnopqrstuvwxyz".charAt(Math.floor(26*Math.random()));return a}
function ob(a,c){for(var b=0,e=0,d=!1,f=a.length,h=c.length,b=0;b<h;b++){d=!1;for(e=0;e<f;e++)c[b]==a[e]&&(d=!0);if(0==d&&e==f)return 0}return 1}mti.o.prototype.Ba=function(a){if((a.ctrlKey||a.metaKey)&&116==a.keyCode){a.preventDefault();a=document.cookie.split(";");for(var c=1;c<=a.length;c++){var b=a[c-1].split("="),e=b[0].substr(b[0].length-2);"1"==b[1]&&"_f"==e&&(document.cookie=b[0]+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT")}document.location.reload(!0)}};
function lb(a,c){var b=W(a,"specialChar"),e=b.length.toString().length;if(c&&"string"==typeof c){for(var d="",f=c.length,h=null,g="",k=[],l=0;l<f;l++)if(h=c.charAt(l),-1<a.a.indexOf(b,escape(h))){if(-1==a.a.indexOf(k,h)){k.push(h);h=a.a.indexOf(b,escape(h));if(h.toString().length<e)var m=Array(1+e).join("0"),h=(m+h).slice(-m.length);g+=h}}else-1==a.a.indexOf(d,h)&&(d+=h);return d+"::"+g}return""}
function db(a,c,b,e){var d="";c=void 0!=b&&void 0!=e?c+("_"+e.charAt(0)+b/100):c+"_n4";a&&a[c]&&(d=a[c]);return 0<d.length?d:null}mti.o.prototype.ha=function(){return this.h};function pb(a,c,b){if(!window.MutationObserver||b){var e="string"==typeof c?document.getElementById(c):c;if(null!==e){b=!0;a.h=[];var d=a.f.projectId,f=a.f.fcURL,h=a.f.ck,g="",k,l,m={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};b=!0;if(T.UseHybrid){b=!1;var q=a.a.getElementById("mti_fontface_"+d);null==q&&(q=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+d}),C(a.a,"head",q));var r=e.getAttribute("data-mtiFont"),u=a.a.getComputedStyle(e);null==r&&
(r=u.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var v=[],n=0;n<a.f.pfL.length;n++)v.push(a.f.pfL[n].fontfamily);if(e.hasChildNodes&&0>a.a.indexOf(v,r))for(n=e.childNodes,w=0;w<n.length&&!(1==n[w].nodeType&&(r=a.a.G(n[w]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(v,r)));w++);for(var v="normal"==u.fontWeight?"400":"bold"==u.fontWeight?"700":u.fontWeight,u=u.fontStyle,n=u.charAt(0)+v/100,p=r.split(","),w=0;w<p.length;w++){b=X(p[w]);for(var t,y=!1,n=0;n<a.f.pfL.length;n++){t=
a.f.pfL[n];var x=t.fontfamily;if(p[w]==x&&t.enableSubsetting)if(void 0!=t.fontWeight&&void 0!=t.fontStyle){if(k=t.fontWeight,l=t.fontStyle,u==t.fontStyle&&v==t.fontWeight){y=!0;n=l.charAt(0)+k/100;b=X(x,n);a.h.push(new R(x,n));break}}else{a.h.push(new R(x));y=!0;break}}if(kb(b)&&y){b=!1;contentIdArray=t.contentIds;enableOtf=t.enableOtf;fFormat=a.aa(contentIdArray);t=x;fontURL=hb(a,contentIdArray,d,!1,f,"",h,t,k,l,null,fFormat,enableOtf);""!=fontURL&&(g+='@font-face{\nfont-family:"'+t+'";',void 0!=
k&&void 0!=l&&(g+="\nfont-style:"+l+";",g+="\nfont-weight:"+k+";"),g+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(k=m[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||(k=m.TTF),g+=" format('"+k+"')"),g+=";}\n");q.styleSheet?q.styleSheet.cssText+=g:q.innerHTML+=g;a.fa[t]=gb(a,"",t);e.style.fontFamily=""+r;e.removeAttribute("data-mtiFont");g="";if(e.hasChildNodes())for(g=e.childNodes,k=0;k<g.length;k++)1==g[k].nodeType&&g[k].getAttribute("data-mtiFont")&&
(g[k].style.fontFamily=g[k].getAttribute("data-mtiFont"),g[k].removeAttribute("data-mtiFont"));if(null!=a.l){var B=new V(document.getElementById(c).parentElement,a.a,a.f.pfL);B.O({},A);mti.bind(a.l,a.l.ia,B.F)()}break}else b=!0}}if(b){var A=nb(),F=B=null,G=[],K=[],D=null!=e?e.parentElement:document.body;(function(){B=new V(D,a.a,a.f.pfL);F=B.O({},A);var b=[];if(void 0!=F)for(var d in F)d+=A,b.push(new R(f));a.R.mti_element_cache=B.F;$a(a,B.ha(),F,A,!0);b=B.F;null!=a.l&&(d=[],d.push(e),mti.bind(a.l,
a.l.ia,d)());for(d=0;d<b.length;d++)for(var f in a.m)-1<a.a.indexOf(a.a.G(b[d]),f)&&(b[d].getAttribute("id")==c||b[d]==c?a.a.U(b[d],f,a.m[f],!1,a.v):va(e,b[d])&&-1<a.a.indexOf(a.a.G(b[d]).replace(/'|"/g,""),f)&&a.a.U(b[d],f,a.m[f],!1,a.v));d=null==a.m[f]?0:a.m[f].length;if(0<a.h.length)for(b=0;b<a.h.length;b++)f=a.h[b].getName()+A,d=null,a.v&&(d=Q(a.h[b])),f=null==d?new R(f):new R(f,d),G.push(f);else for(b=0;b<d;b++)a.v?G.push(new R(a.m[f][b],"i6")):G.push(new R(a.m[f][b])),-1==a.a.indexOf(a.ua,f)&&
(a.ua.push(f),a.v?K.push(new R(a.m[f][b],"i6")):K.push(new R(a.m[f][b])))})();1==T.RemoveMTIClass&&setTimeout(function(){qb(a,"mti_font_element"+A)},fa.Ca);b={};T.UseHybrid&&0<G.length&&(b.fontactive=function(){ab(a,a.ba,!0)},b.fontinactive=function(){ab(a,a.ba,!0)});1==T.EnableCustomFOUTHandler&&Sa(new Ra(a.c,a.a,new Fa(a.a,document.documentElement,b),fa.Ca),G,{},{},!1)}}}}mti.Fa=function(a){this.bb=a};mti.Fa.prototype={hb:function(a,c){pb(this.bb,a,c)}};
mti.o.prototype.za=function(){var a=this,c="",b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ");if(window.MutationObserver){var e=new MutationObserver(function(b){b.forEach(function(b){if("characterData"==b.type)null!=b.target.parentNode&&(d=b.target.parentNode,"undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=b.target.parentNode.id&&void 0!=typeof b.target.parentNode.id&&
"undefined"!==typeof document.getElementById(b.target.parentNode.id)&&null!=document.getElementById(b.target.parentNode.id)&&(c=document.getElementById(b.target.parentNode.id).getAttribute("data-mti-otf")),void 0!=typeof c&&"mti-otf"!=c&&Y(a,b.target.parentNode)):setTimeout(function(){d.removeAttribute("isRender")},0));else if("attributes"==b.type)if("style"==b.attributeName){var d=b.target;""==d.style.fontFamily&&""==d.style.fontWeight&&""==d.style.fontStyle||"BESb\uc5d0swy"==d.innerHTML||"BESbswy"==
d.innerHTML||("undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=d.id&&""!=d.id&&void 0!=typeof d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d=null!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d)):setTimeout(function(){d.removeAttribute("isRender")},0))}else"class"==
b.attributeName&&rb(sb(b.target.classList))?Y(a,b.target):"id"==b.attributeName&&-1<b.target.id.indexOf("mtiSelector")&&Y(a,b.target);else if("childList"==b.type&&0<b.addedNodes.length)for(var e=0;e<b.addedNodes.length;e++)if(d=b.addedNodes[e],3==d.nodeType&&(d=d.parentNode),"undefined"!==typeof d&&null!=d&&3!=d.nodeType){var k=d.tagName;"HTML"!=k&&"HEAD"!=k&&"TITLE"!=k&&"STYLE"!=k&&"LINK"!=k&&"META"!=k&&"BASE"!=k&&"IMG"!=k&&"HR"!=k&&"BR"!=k&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&
"undefined"!==typeof d.className&&"function"===typeof d.className.indexOf&&-1==d.className.indexOf("firebugLayoutBox")&&(null!=d.id&&""!=d.id&&void 0!=typeof d.id?null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d="undefined"!==typeof d.id&&null!=d.id&&""!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d))}});tb(a,!0)});document.body&&e.observe(document.body,{childList:!0,characterData:!0,
subtree:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["style","class","id"]})}else e=function(a,c){var b=document;b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent("on"+a,c)},e("DOMNodeInserted",function(d){d=d.target;if(1>d.childNodes.length||""==d.innerHTML)return!1;void 0!=typeof d&&null!=d&&3==d.nodeType&&(d=void 0!==d.parentElement?d.parentElement:d.parentNode);if(0<a.a.indexOf(b,d.nodeName.toLowerCase()))return!1;if(void 0!=typeof d&&null!=d&&1==d.nodeType){var e=d.tagName;
"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&(void 0!=typeof d.id&&null!=d.id&&""!=d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):void 0!=typeof d.getAttribute&&void 0!=typeof d&&null!=d&&""!=d&&(c=d.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=d&&(Y(a,d),tb(a,!1)))}}),e("DOMAttrModified",
function(b){if("style"==b.attrName){var e=b.target;"BESb\uc5d0swy"!=e.innerHTML&&"BESbswy"!=e.innerHTML&&("undefined"!==typeof e.getAttribute("isRender")&&"true"!==e.getAttribute("isRender")?(e.setAttribute("isRender","true"),void 0!=typeof e.id&&null!=e.id&&""!=e.id?void 0!=typeof document.getElementById(e.id)&&null!=document.getElementById(e.id)&&(c=document.getElementById(e.id).getAttribute("data-mti-otf")):void 0!=typeof e.getAttribute("data-mti-otf")&&null!=e&&""!=e&&(c=e.getAttribute("data-mti-otf")),
"mti-otf"!=c&&""!=e&&(Y(a,e),tb(a,!1))):setTimeout(function(){e.removeAttribute("isRender")},0))}else"class"==b.attrName&&rb(sb(b.target.className))?(Y(a,b.target),tb(a,!1)):"id"==b.attrName&&-1<b.target.id.indexOf("mtiSelector")&&(Y(a,b.target),tb(a,!1))}),e("DOMCharacterDataModified",function(b){b=b.target;void 0!=typeof b&&null!=b&&3==b.nodeType&&(b=b.parentElement);if(void 0!=typeof b&&null!=b&&1==b.nodeType){var e=b.tagName;"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&
"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=b.innerHTML&&"BESbswy"!=b.innerHTML&&(void 0!=typeof b.id&&null!=b.id&&""!=b.id?null!=document.getElementById(b.id)&&(c=document.getElementById(b.id).getAttribute("data-mti-otf")):void 0!=typeof b&&null!=b&&""!=b&&(c=b.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=b&&(Y(a,b),tb(a,!1)))}})};
function Y(a,c){if(void 0!=typeof c&&null!=c){var b,e,d="",f=!1;"string"==typeof c?(b=document.getElementById(c),null!=b&&(e=b.parentNode),null!=e&&(d=b.getAttribute("id")),-1==a.a.indexOf(a.D,c)&&-1==a.a.indexOf(a.D,d)&&(a.D.push(c),f=!0)):-1==a.a.indexOf(a.D,c)&&-1==a.a.indexOf(a.D,c.parentElement)&&(a.D.push(c),f=!0);f&&1==T.EnableCustomFOUTHandler&&(c="string"==typeof c?document.getElementById(c):c,1==c.nodeType&&ub(a,c).u&&vb(a,c))}}mti.o.prototype.Aa=null;
function tb(a,c){var b=50;c||(b=0);a.f.enableOtf&&(b=0);null!=a.Aa&&clearTimeout(a.Aa);a.Aa=setTimeout(function(){if(-1<a.D.length){var b="",c=a.D.length;if(!(1>c)){for(var f=0;f<c;f++){var h="string"==typeof a.D[f]?document.getElementById(a.D[f]):a.D[f];if(void 0!=typeof h&&null!=h){var b=pa(a.a,h),g=new V(h,a.a,a.f.pfL),k=g.O(h),g=g.F,l=ub(a,h);l.u?""!=b?wb(a,a.D[f],b,l,k,g):(b="_n4",a.j&&(b=l.fontStyle.charAt(0)+l.fontWeight/100),null!=k&&(b=k[l.V+b],""!=b&&wb(a,a.D[f],b,l,k,g))):!l.u&&null!=h&&
h.hasChildNodes&&(l=xb(a,h),b=pa(a.a,l.node),g=new V(l.node,a.a,a.f.pfL),k=g.O(l.node),g=g.F,l.u&&wb(a,l.node,b,l,k,g))}}a.D=[]}}},b)}
function ub(a,c){if(1!=c.nodeType)return{u:!1};var b=a.a.getComputedStyle(c),e="test",d="normal",f="100";if(void 0!=typeof b&&null!=b)if(e=b.fontFamily,d=b.fontStyle,f="normal"==b.fontWeight?"400":"bold"==b.fontWeight?"700":b.fontWeight,b=null!=e?e.split(","):"",b instanceof Array)for(e=0;e<b.length;e++)for(var h=0;h<a.f.pfL.length;h++){var g=a.f.pfL[h],k=g.fontfamily,l=g.enableSubsetting,m=g.fontStyle,q=g.fontWeight,g=g.enableOtf;if(k==H(b[e])&&(l||g))if(a.j){if(m==d&&q==f)return{u:!0,V:k,fontWeight:f,
fontStyle:d}}else return{u:!0,V:k}}else for(e=0;e<a.f.pfL.length;e++)if(g=a.f.pfL[e],k=g.fontfamily,l=g.enableSubsetting,m=g.fontStyle,q=g.fontWeight,g=g.enableOtf,l||g)if(a.v){if(m==d&&q==f)return{u:!0,V:k,fontWeight:f,fontStyle:d}}else if(k==H(b))return{u:!0,V:k};return{u:!1}}function xb(a,c){var b={u:!1,V:"testFont"};if(1==c.nodeType&&(b=ub(a,c),b.u))return b.node=c,b;for(var e=c.childNodes,d=e.length,f=0;f<d;f++){var h=e[f];if(1==h.nodeType&&(b=xb(a,h),b.u))break}return b}
function yb(a,c,b){var e="string"==typeof c?document.getElementById(c):c;if(null!==e){var d=!0,f=[];a.h=[];var h=a.f.projectId,g=a.f.fcURL,k=a.f.ck,l="",m,q,d=!0;if(T.UseHybrid){var d=!1,r=a.a.getElementById("mti_fontface_"+h);null==r&&(r=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+h}),C(a.a,"head",r));var u=e.getAttribute("data-mtiFont"),v=a.a.getComputedStyle(e);null==u&&(u=v.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var n=[],p=0;p<a.f.pfL.length;p++)n.push(a.f.pfL[p].fontfamily);
if(e.hasChildNodes&&0>a.a.indexOf(n,u))for(p=e.childNodes,t=0;t<p.length&&!(1==p[t].nodeType&&(u=a.a.G(p[t]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(n,u)));t++);for(var n="normal"==v.fontWeight?"400":"bold"==v.fontWeight?"700":v.fontWeight,v=v.fontStyle,w=v.charAt(0)+n/100,u=u.split(","),t=0;t<u.length;t++){for(var y,p=0;p<a.f.pfL.length;p++){y=a.f.pfL[p];var x=y.fontfamily,B=X(x);if(u[t]==x&&y.enableSubsetting)if(a.j){if(m=y.fontWeight,q=y.fontStyle,v==y.fontStyle&&n==y.fontWeight){w=
q.charAt(0)+m/100;B=X(x,w);a.h.push(new R(x,w));f.push(new R(x,w));break}}else{w="n4";a.h.push(new R(x));f.push(new R(x));break}}kb(B)&&(d=!1,-1==a.a.indexOf(a.W,x+"_"+w)&&(contentIdArray=y.contentIds,enableOtf=y.enableOtf,fFormat=a.aa(contentIdArray),fontURL=hb(a,contentIdArray,h,!1,g,"",k,x,m,q,null,fFormat,enableOtf),""!=fontURL&&(l+='@font-face{\nfont-family:"'+x+'";',a.j&&(l+="\nfont-style:"+q+";",l+="\nfont-weight:"+m+";"),l+='\nsrc:url("'+fontURL+'")',l+=";}\n",a.fa[x+"_"+w]=gb(a,"",x+"_"+
w))));if(""!=l){r.styleSheet?r.styleSheet.cssText+=l:r.innerHTML+=l;e.removeAttribute("data-mtiFont");p="";if(e.hasChildNodes())for(var p=e.childNodes,A=0;A<p.length;A++)1==p[A].nodeType&&p[A].getAttribute("data-mtiFont")&&(p[A].style.fontFamily=p[A].getAttribute("data-mtiFont"),p[A].removeAttribute("data-mtiFont"));if(null!=a.l){var F=new V(null!=e&&e!=document.body?e.parentElement:document.body,a.a,a.f.pfL);F.O({},G);mti.bind(a.l,a.l.ia,F.F)()}}else d=!0}}if(d){var G=nb(),K=F=null,f=[],D=[],U=null!=
e&&e!=document.body?e.parentElement:document.body;if(null==e.parentElement||b)U=document.body;(function(){F=new V(U,a.a,a.f.pfL);K=F.O({},G);if(void 0!=K)for(var b in K)26<b.length&&(a.w[b]||(a.w[b]="mtiFont"+a.Pa++)),void 0!==a.w[b]&&""!==a.w[b]&&(b=a.w[b]),b+=G;a.R.mti_element_cache=F.F;$a(a,F.ha(),K,G,!0);b=F.F;null!=a.l&&mti.bind(a.l,a.l.ia,b)();for(var d,g,h=0;h<b.length;h++){var k=a.a.getComputedStyle(b[h]),l;for(l in a.m)a.j&&(d=l.slice(-2),l=l.slice(0,-3),g=k.fontWeight,g=k.fontStyle.charAt(0)+
g/100),-1<a.a.indexOf(a.a.G(b[h]),l)&&(a.j?d==g:1)&&(b[h].getAttribute("id")==c||b[h]==c?a.a.U(b[h],l,a.m[l+(a.j?"_"+d:"")],!1,a.v):va(e,b[h])&&-1<a.a.indexOf(a.a.G(b[h]).replace(/'|"/g,""),l)&&(a.j?d==g:1)&&a.a.U(b[h],l,a.m[l+(a.j?"_"+d:"")],!1,a.v))}b=null==a.m[l]?0:a.m[l].length;if(0<a.h.length)for(d=0;d<a.h.length;d++)a.h[d].enableSubsetting&&(l="n4",a.j&&(l=Q(a.h[d])),b=(void 0!==a.w[a.h[d].getName()+"_"+l]?a.w[a.h[d].getName()+"_"+l]:a.h[d].getName())+G,l=null!=l?new R(b,l):new R(b),f.push(l));
else for(d=0;d<b;d++)a.j?f.push(new R(a.m[l][d],"i6")):f.push(new R(a.m[l][d])),-1==a.a.indexOf(a.ua,l)&&(a.ua.push(l),a.j?D.push(new R(a.m[l][d],"i6")):D.push(new R(a.m[l][d])))})();1==T.RemoveMTIClass&&setTimeout(function(){qb(a,"mti_font_element"+G)},5E3);b={};0<f.length&&(b.fontactive=function(b,c,d){T.UseHybrid&&ab(a,a.ba,!0);for(var e=0;e<window.MonoTypeWebFonts._fontActiveEventList.length;e++)d=b.slice(0,-5),window.MonoTypeWebFonts._fontActiveEventList[e].call(window.MonoTypeWebFonts,b,c,d)},
b.inactive=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._inActiveEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._inActiveEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.fontloading=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._fontLoadingEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._fontLoadingEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.active=function(){for(var a=0;a<window.MonoTypeWebFonts._activeEventList.length;a++)window.MonoTypeWebFonts._activeEventList[a].call(window.MonoTypeWebFonts)});
1==T.EnableCustomFOUTHandler&&Sa(new Ra(a.c,a.a,new Fa(a.a,document.documentElement,b),5E3),f,{},{},!1)}}}
function wb(a,c,b,e,d,f){var h=c;"string"==typeof c&&(h=document.getElementById(h));e=c==e.node?!0:!1;var g="",g="";if(null!=d)for(var k in d){if(""!=d[k]){var l=k.slice(0,-3),m=k.slice(-2),q=l;void 0!==a.w[k]&&(l=a.w[k]);b+=void 0!==d[l+"_"+m]?d[l+"_"+m]:"";var g=wa(b),g=g.split("").sort().join(""),g=gb(a,g,l+"abcde"+(a.j?"_"+m:""),!0),r=a.fa[l+"_"+m];if(-1==a.a.indexOf(a.W,k))if(T.UseHybrid)if(kb(X(q,m)))yb(a,c,e);else if(g!=r){for(var u in f)g=ub(a,f[u]),g.u&&(b=pa(a.a,f[u]),""!=b&&(g=gb(a,"",
l+"abcde_"+m,!0),q=wa(b).split("").sort().join(""),g=wa(g),ob(g,q)||yb(a,f[u],e)));yb(a,c,e)}else null!=a.l&&zb(a,c),-1<a.oa.indexOf(k+"_f")&&-1==a.W.indexOf(k)&&(textCollector=new V(h,a.a,a.f.pfL),d=textCollector.O({}),$a(a,textCollector.ha(),d));else if(g!=r)yb(a,c,e);else{l=a.a.G(h);m=h.getAttribute("data-mtiFont");r=!0;g=ub(a,h);g.u&&a.j&&(r=a.a.getComputedStyle(h),l=r.fontFamily,fntStyle=r.fontStyle,fntWeight=r.fontWeight,r=fntStyle==g.fontStyle&&fntWeight==g.fontWeight?!0:!1);if(-1==l.indexOf(a.Z[k])&&
-1<l.indexOf(m)&&0==a.Z[k].indexOf(m)&&r)a.a.U(h,q,a.Z[k],!1,!1);else for(u in f)g=ub(a,f[u]),g.u&&g.V===q&&(l=a.a.G(f[u]),r=!0,m="n4",a.j&&(r=a.a.getComputedStyle(f[u]),l=r.fontFamily,fntStyle=r.fontStyle,fntWeight=r.fontWeight,m=g.fontStyle.charAt(0)+g.fontWeight/100,r=fntStyle==g.fontStyle&&fntWeight==g.fontWeight?!0:!1),void 0!==a.Z[q+"_"+m]&&-1==l.indexOf(a.Z[q+"_"+m])&&r&&a.a.U(f[u],q,a.Z[q+"_"+m],!1,!1));null!=a.l&&zb(a,c)}else null!=a.l&&zb(a,c)}}else null!=a.l&&zb(a,c);1==T.EnableCustomFOUTHandler&&
qb(a,"mti_hide_element")}function zb(a,c){var b="string"==typeof c?document.getElementById(c):c,e=new V(null!=b?c.parentElement:document.body,a.a,a.f.pfL);e.O({});e=e.F;0==e.length&&e.push(b);mti.bind(a.l,a.l.ia,e)()}function sb(a){for(var c=[],b=a.length>>>0;b--;)c[b]=a[b];return c}
function vb(a,c){var b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),e=ub(a,c),d,f;e.u&&(d=e.V,f="n4",a.j&&(f=e.fontStyle.charAt(0)+e.fontWeight/100));if(void 0!==c&&null!==c&&""!==c&&c.tagName&&1===c.nodeType&&0>a.a.indexOf(b,c.tagName.toLowerCase())){var h=pa(a.a,c),b=!1;""!=h.replace(/\s/g,"")&&e.u&&(500>h.length?(e=h.split("").sort().join(""),gb(a,e,d+"abcde"+(a.j?"_"+f:""),!0)!=a.fa[d+"_"+f]&&(b=!0)):b=!0,b&&E(c,"mti_hide_element"));for(c=
c.firstChild;c;)vb(a,c),c=c.nextSibling}}function rb(a){var c,b=a.length,e=!1;for(c=0;c<b;c++)if(-1<a[c].indexOf("mtiSelector")){e=!0;break}return e};function kb(a){a=a.replace(/\s+/g,"%20");a=document.cookie.split(a+"=");var c=null;2==a.length&&(c=a.pop().split(";").shift());return 1==c?!0:!1}
function gb(a,c,b,e){var d="";e&&(a.v?(d=b.substring(b.length-3,b.length),b=b.substring(0,b.length-8)):b=b.substring(0,b.length-5));mb(b,a.w)&&(b=mb(b,a.w).slice(0,-3));b+=d;if("undefined"!==typeof Storage){a:{var f;try{f=window.localStorage.getItem(b)}catch(h){console&&console.log("MTI_webfont_service::localStorage.getItem error::"+h.message);a=!1;break a}a=null==f?!1:f.length>c.length?ob(f,c)?f:!1:!1}if(0==a&&c){a=c;try{var g=window.localStorage.getItem(b);null!=g&&(a+=g);a=wa(a).split("").sort().join("");
window.localStorage.setItem(b,a)}catch(k){console&&console.log("MTI_webfont_service::localStorage.setItem error::"+k.message)}}else if(0<a.length)return a}return c};function qb(a,c){for(var b=sa(a.a,c),e=new RegExp(c,"ig");0<b.length;){for(var d=0;d<b.length;d++)1==b[d].className.split(" ").length?b[d].removeAttribute("class"):b[d].className=b[d].className.replace(e," ").replace(/^\s+|\s+$/g,"");b=sa(a.a,c)}}
mti.o.prototype.U=function(a,c,b,e,d){var f=this.G(a).split(","),h=[];if(b instanceof Array){for(var g in b)b.hasOwnProperty(g)&&h.push(b[g]);e&&(d&&(b=oa(this,a),e=na(this,a),h.push(c+"_"+b.charAt(0)+e/100)),a.style.fontWeight="",a.style.fontStyle="");for(g in f)f.hasOwnProperty(g)&&h.push(f[g]);h=ua(h);a.style.fontFamily=h;a.setAttribute("data-mtiFont",c)}};
function bb(a,c){if(!0===mti.o.b)c();else{var b=a.a.C;if("MSIE"==a.c.getName()){var e=!1,d=function(){e||(e=!0,c(),mti.o.b=!0)};(function(){try{if("msie"==a.K&&11<=a.version.i?b.documentElement.scrollLeft:b.documentElement.doScroll("left"),"complete"!=b.readyState){setTimeout(arguments.callee,50);return}}catch(c){setTimeout(arguments.callee,50);return}d()})();b.onreadystatechange=function(){"complete"==b.readyState&&(b.onreadystatechange=null,d())}}else"AppleWebKit"==a.c.Va&&525>a.c.Ua.i?function(){-1<
["loaded","complete"].indexOf(b.readyState)?(c(),mti.o.b=!0):setTimeout(arguments.callee,50)}():b.addEventListener?"loading"==b.readyState?b.addEventListener("DOMContentLoaded",function(){c();mti.o.b=!0},!1):window.addEventListener("load",function(){c();mti.o.b=!0},!1):window.onload=function(){c();mti.o.b=!0}}}
function ab(a,c,b){"complete"==document.readyState?setTimeout(function(){c.apply(a,[a.h,b,!1])},500):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&setTimeout(function(){c.apply(a,[a.h,b,!1])},500)});document.addEventListener?document.addEventListener("keydown",function(b){a.Ba.apply(a,[b])}):window.attachEvent?window.attachEvent("onkeydown",function(b){a.Ba.apply(a,[b])}):document.addEventListener("keydown",function(b){a.Ba.apply(a,[b])})};new function(){function a(c,d){if(!(this instanceof a))return(new a(c)).Ga(d);g||(this.Ga=q[c]||(q[c]=new b(c)));this.b=c}function c(a){var b=arguments;return a.replace(/\$(\d)/g,function(a,c){return b[c]})}function b(a){with(this){var b="";do i=nqp=0,b+=c("n=c;$1q:do{$2}while(false);",srt?"s=0;":"",type(a,c(srt?"for(x=r.length;s<x;z=s+((x-s)/2)|0,($1)?s=z+1:x=z);if(s<r.length)r.splice(s++,0,$2);else r[s++]=$2;":"r[s++]=$2;",m?"r[z].compareDocumentPosition(n)&4":"h[r[z].LLn]<h[n.LLn]","pe?pe.call(this,n):n"),
0,"*"));while(a=nqp);b=c("var r=[],s=0,n,x,y,z,d=c?c.ownerDocument||c.document||c:c=document,pe=this.patchElement,pa=this.patchArray$1$2;$3return pa?pa.call(this,r):r;",0<dup?",h={}":"",idx?u?",LLi=d.LLi||(d.LLi=++Selector.guid)":",LLi=++Selector.guid":"",b);return new Function("c",b)}}a.prototype={constructor:a,Ga:function(a){var b=this.s,c=this.g,d=this.b;a=b?r.call((a||f).querySelectorAll(d),b,this):Array.prototype.slice.call((a||f).querySelectorAll(d));return c?c.call(this,a):a},toString:function(){return this.b},
toSource:function(){return'new Selector("'+this.b+'")'}};window.Selector=a;with(navigator.userAgent){var e=-1!=indexOf("MSIE")&&-1==indexOf("Opera");-1!=indexOf("Gecko")&&indexOf("KHTML");var d=-1!=indexOf("AppleWebKit")}var f=document,h=f.documentElement,g=!!f.querySelectorAll,k=!!h.children,l=k&&h.children.b&&!d,m=!!h.compareDocumentPosition,q={},r=Array.prototype.map||function(a,b){for(var c=this.length,d=Array(c);0<=--c;)d[c]=a.call(b,this[c],c,this);return d};with(f.implementation)var u=f.addEventListener&&
(hasFeature("MutationEvents","2.0")||hasFeature("Events","2.0")&&hasFeature("Core","2.0"));a.b=0;a.g=function(a,b,c,d,e){var f=b.parentNode,g="LLi#"+e,h="LLi$"+e;if(!f)return Number.NaN;if(!b[g]||b.Ea!=a){for(var l=f.firstChild,k=0;l;l=l.nextSibling)l[d]==e&&(l[g]=++k,l.Ea=a);f[h]=k}return c?1+f[h]-b[g]:b[g]};u&&(d=function(b){with(b.target)2!==nodeType&&(ownerDocument.Ea=++a.b)},f.addEventListener("DOMNodeInserted",d,!1),f.addEventListener("DOMNodeRemoved",d,!1));b.prototype={type:function(a,b,d,
f,g){with(this){a=/^\s*([\w-]+|\*)?(.*)/.exec(a);var h=a[1]||"*";d||" "!=g||dup||(dup=1);b=pred(a[2],b,d,h,g);switch(g){case ">":return l&&"*"!=h?c('for(var n$1=n.children.tags("$2"),i$1=0;n=n$1[i$1++];){$3}',++i,h,b):c(k?"for(var n$1=n.children,i$1=0;n=n$1[i$1++];)$2{$3}":"for(n=n.firstChild;n;n=n.nextSibling)$2{$3}",++i,"*"!=h?'if(n.nodeName==="'+h.toUpperCase()+'")':!k||e?"if(n.nodeType===1)":"",b);case "+":return c("while(n=n.nextSibling)if(n.node$1){$2break}else if(n.nodeType===1)break;","*"==
h?"Type===1":'Name==="'+h.toUpperCase()+'"',b);case "~":return c("while(n=n.nextSibling)if(n.node$1){$3}else if(n.node$2)break;","*"==h?"Type===1":'Name==="'+h.toUpperCase()+'"',"*"==f?"Type===1":'Name==="'+f.toUpperCase()+'"',b);default:return"object"==typeof b?String(b):d?"*"==h?b:c('if(n.nodeName!="$1"){$2}',h.toUpperCase(),b):c('for(var n$1=n.getElementsByTagName("$2"),i$1=0;n=n$1[i$1++];)$3{$4}',++i,h,e&&"*"==h?"if(n.nodeType===1)":"",b)}}}}};mti.da=function(a,c,b){this.ya=!1;this.a=a;this.c=c;this.f=b;a=b.pfL;this.T=[];this.wa={};this.Ra=b.otfJsParentUrl;for(b=0;b<a.length;b++){var e=a[b];e.enableOtf&&this.T.push(e)}this.ya="MSIE"==c.getName()&&8>c.ka};function Ab(a){return null==a?!1:"BODY"!=a.nodeName&&"class-with-otf-main"==a.className?!0:!1}
function Bb(a){var c=a.c.getName();if("Firefox"!=c&&"MSIE"!=c&&"Chrome"!=c){for(var c="",b=document.getElementsByTagName("style"),e=0;e<b.length;e++)c+=b[e].innerHTML;var b=document.getElementsByTagName("link"),d;window.XMLHttpRequest?d=new XMLHttpRequest:d=new ActiveXObject("Microsoft.XMLHTTP");for(e=0;e<b.length;e++)if(void 0!=b[e].attributes.getNamedItem("rel")&&"stylesheet"==b[e].attributes.getNamedItem("rel").value.toLowerCase()){var f=b[e].attributes.getNamedItem("href").value;try{-1==f.indexOf("fast.fonts.net/t/1.css")&&
(d.open("GET",f,!1),d.send(null),c+=d.responseText)}catch(h){}}for(var g=function(a){return a.replace(/^\s+|\s+$/g,"")},c=function(a){a=a.replace(/(\/\*([^*]|(\*+([^*/])))*\*+\/)/gm,"");a=a.replace(/(<\!\[CDATA\[([^\]]|(\]+([^>])))*\]+>)/gm,"");a=a.replace(/[\t]+/g," ").replace(/[ ][ ]/g," ");a=a.replace(/[\r\n]/g,"");return g(a)}(c),e=c.indexOf("font-feature-settings");-1!=e;)if(d=c.lastIndexOf("{",e),b=c.indexOf("}",e),-1!=d&&-1!=b){f=c.substring(d,b).split(";");if(0<f.length)for(e=0;e<f.length;e++){var k=
f[e],l=k.indexOf(":");if(-1!=l){var m=g(k.substring(0,l));if("font-feature-settings"==m||"-o-font-feature-settings"==m){var m=c.lastIndexOf("}",d),q="",q=-1==m?c.substring(0,d):c.substring(m+1,d);if(0<q.length){q=g(q);a.wa[q]=g(k.substring(l+1));break}}}}e=c.indexOf("font-feature-settings",b)}else e+=length("font-feature-settings")}}mti.da.prototype.ia=function(a){this.ya||(Bb(this),this.La(a))};
mti.da.prototype.load=function(a){this.Ja={};this.Qa=0;var c=this;if(!this.ya){Bb(c);for(var b=0;b<this.T.length;b++){var e=this.T[b],d="otf_"+e.variationId;Cb(this,this.Ra+e.otfJsContentId+"/"+d+"OTFFeatDisabled.js",function(){c.Qa++;if(c.Qa==c.T.length){for(var b=0;b<c.T.length;b++){e=c.T[b];d="otf_"+e.variationId;for(var h=window[d+"OTFFeatLookupIndex"](),g=window[d+"OTFFeatDisable"](),k=[],l=0;l<h.length;l++){var m=h[l];-1==g.indexOf(m)&&k.push(m)}c.Ja[e.variationId]=k}mti.bind(c,c.La,a)()}})}}};
function Db(a,c){var b=a.a.G(c),e=oa(a.a,c),d=na(a.a,c),d="normal"==d?400:"bold"==d?700:d,b=(b||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=b)for(var f=new RegExp("^("+b+")$","ig"),h=0;h<a.T.length;h++){var g=a.T[h];if(f.test(g.fontfamily.replace(/^\s|\s$/g,""))){if(void 0==g.fontWeight||void 0==g.fontStyle||g.fontWeight==d&&g.fontStyle===e)return g;f=new RegExp("^("+b+")$","ig")}}return null}
function Eb(a,c,b,e,d){function f(b){var c,d=!1;c="Firefox"==a.c.getName()?b.indexOf("moz-font-feature-settings"):"MSIE"==a.c.getName()?b.indexOf("ms-font-feature-settings"):"Chrome"==a.c.getName()?b.indexOf("webkit-font-feature-settings"):"Opera"==a.c.getName()?b.indexOf("o-font-feature-settings"):b.indexOf("font-feature-settings");if(-1!=c)return b=b.substr(c),b=b.substr(0,b.indexOf(";")),h(b);"undefined"!=typeof Userkernstring&&(d=!0);return[!1,"","",d]}function h(c){var d=!1,e="",f="",g=!1;if(null!=
c&&""!=c)for(var h=a.Ja[b.variationId],k=0;null!=h&&k<h.length;k++){var p=c.indexOf(h[k]);if(-1!=p){var w=c.substr(p+4),p=w.indexOf(",");-1!=p&&(w=w.substring(0,p));-1==w.indexOf("off")&&-1==w.indexOf("0")&&(""!=f&&(f+=" "),f+=w.substr(2),""==f&&(f+=1),""!=e&&(e+=" "),e+=h[k],d=!0)}}"undefined"!=typeof Userkernstring&&(g=!0);return[d,e,f,g]}var g=a.c.getName(),k="font-feature-settings";"Firefox"==g?k="MozFontFeatureSettings":"MSIE"==g?k="-ms-font-feature-settings":"Chrome"==g?k="-webkit-font-feature-settings":
"Opera"==g&&(k="-o-font-feature-settings");if("Firefox"==g||"MSIE"==g||"Chrome"==g)return c.currentStyle?h(c.currentStyle[k]):document.defaultView&&document.defaultView.getComputedStyle?h(document.defaultView.getComputedStyle(c,"")[k]):h(c.style[k]);g=!1;"undefined"!=typeof Userkernstring&&(g=!0);g=[!1,"","",g];for(k=e.length;0<=k;k--)if(e[k]==c){g=h(a.wa[d[k]]);break}null!=c.attributes&&(c=c.attributes.getNamedItem("style"),null!=c&&(c=f(c.value),c[0]&&(g=c)));return g}
mti.da.prototype.La=function(a){var c="",b="",e=!1,d=[],f=[],h;for(h in this.wa)Selector(h,document).forEach(function(a){d.push(a);f.push(h)});for(var g=[],k=[],l=0;l<a.length;l++){var b=a[l],m=Db(this,b);if(null!=m){var q="otf_"+m.variationId,r=Eb(this,b,m,d,f);if(r[0]||r[3])if(g.push(b),k.push(r),e=!0,r[0])for(var r=r[1].split(" "),u=0;u<r.length;u++)b=this.Ra+m.otfJsContentId+"/"+q+r[u]+".js",null==window[q+r[u]]&&-1==c.indexOf(b)&&(c+=b+" ")}}a=c.split(" ");var v=a.length-1,n=0,p=this;if(0<v)for(l=
0;l<a.length-1;l++)Cb(this,a[l],function(){n++;n==v&&mti.bind(p,p.Ha,g,k)()});else e&&mti.bind(p,p.Ha,g,k)()};
mti.da.prototype.Ha=function(a,c){for(var b=[],e=[],d=[],f=[],h="",g="",k="",l="",m=[],q=0,r=0,u=0;u<a.length;u++){var v=a[u];if(window.getComputedStyle){var h=window.getComputedStyle(v,"").fontSize,k=window.getComputedStyle(v,"").textDecoration,n=window.getComputedStyle(v,"").color.match(/\d+/g);null!=n&&(g="#"+(9<parseInt(n[0])?parseInt(n[0]).toString(16):"0"+parseInt(n[0]).toString(16))+(9<parseInt(n[1])?parseInt(n[1]).toString(16):"0"+parseInt(n[1]).toString(16))+(9<parseInt(n[2])?parseInt(n[2]).toString(16):
"0"+parseInt(n[2]).toString(16)))}else h=v.currentStyle.fontSize,k=v.currentStyle.textDecoration,n=v.currentStyle.color,null!=n&&(g="#"+(9<parseInt(n[0])?parseInt(n[0]).toString(16):"0"+parseInt(n[0]).toString(16))+(9<parseInt(n[1])?parseInt(n[1]).toString(16):"0"+parseInt(n[1]).toString(16))+(9<parseInt(n[2])?parseInt(n[2]).toString(16):"0"+parseInt(n[2]).toString(16)));var p=c[u],n=Db(this,v);if(null!=n&&"undefined"!=typeof p&&"undefined"!=typeof p[1]&&""!=p[1])for(var n="otf_"+n.variationId,w=
p[1].split(" "),p=p[2].split(" "),t=0;t<w.length;t++){v.innerHTML=v.innerHTML.replace(/&nbsp;/g,"<space>").replace(/&amp;/g,"<amp>").replace(/&lt;/g,"<lt>").replace(/&gt;/g,"<gt>").replace(/&quot;/g,"<quot>");"mti-otf"!==v.getAttribute("data-mti-otf")?v.setAttribute("data-mti-otf","mti-otf"):setTimeout(function(){v.removeAttribute("data-mti-otf")},500);if("kern"==w[t])window[n+w[t]](v,h);else window[n+w[t]](v,p[t]);v.innerHTML=v.innerHTML.replace(/<space>/g,"&nbsp;").replace(/<amp>/g,"&amp;").replace(/<lt>/g,
"&lt;").replace(/<gt>/g,"&gt;").replace(/<quot>/g,"&quot;")}if(null!=v&&Ab(v.parentNode)){n=v.innerHTML.replace(/\s+/g," ");e[q]!=h?(0!=u&&q++,b[q]=n,e[q]=h):b[q]+=n;n=n.split(/<[\/]?\s*\w.*?>/g);w="";for(p=0;p<n.length;++p)w+=n[p];n=w.length;for(w=0;w<n;w++)d[r]=h,f[r]=g,m[r]=k,r++}}for(var u=document.getElementsByTagName("*"),y,e=0;e<u.length;e++)if("class-with-otf-main"==u[e].className){y=u[e];break}if(void 0!=y&&void 0!=typeof Userkernstring){e=y.innerHTML;y.innerHTML="";for(u=0;u<=q;u++)"undefined"!=
typeof b[u]&&""!=b[u]&&(l+=b[u]);"undefined"!=typeof l&&""!=l&&(l=l.replace(/&nbsp;/g,"<space>").replace(/&amp;/g,"<amp>").replace(/&lt;/g,"<lt>").replace(/&gt;/g,"<gt>").replace(/&quot;/g,"<quot>"),b=mti_K(l,1,d,0,0,2,f,m),y.innerHTML=0==b[1]?e:y.innerHTML+b[0].replace(/<space>/g,"&nbsp;").replace(/<amp>/g,"&amp;").replace(/<lt>/g,"&lt;").replace(/<gt>/g,"&gt;").replace(/<quot>/g,"&quot;"))}};
function Cb(a,c,b){var e=document.createElement("script");e.type="text/javascript";e.setAttribute("src",c);document.all&&(9>a.c.ka||9<a.c.ka)?e.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||b()}:e.onload=b;document.getElementsByTagName("head")[0].appendChild(e)}
window.mti_CR=function(){for(var a=arguments[0].replace(/(\r\n|\n|\r)/g,""),c=a.split(/<[\/]?\s*\w.*?>/g),b="",e=arguments[1],d=arguments[2],f,h,g,k,l,m,q,r,u=0;u<c.length;u++){k=a.search(/<[\/]?\s*\w.*?>/g);var v="";-1!=k&&(v=a.substring(k,a.indexOf(">")+1));-1!=a.indexOf(">")&&(a=a.substring(a.indexOf(">")+1));var n=c[u];r=0;for(;r<n.length;r++)b:for(q=0;q<d;q++){f=e["R"+q];g=f.B;if(r<g)continue b;k=f.I;l=f.L;var p=f.IO,w=f.BO,t=f.LO,y=f.M;for(m=0;m<y;m++)if(h=n.charCodeAt(r+m),m<k&&"undefined"==
typeof p["o"+(m+1)]["u"+h]||m<g&&"undefined"==typeof w["o"+(m+1)]["u"+n.charCodeAt(r-g+m)]||m<l&&"undefined"==typeof t["o"+(m+1)]["u"+n.charCodeAt(r+k+m)])continue b;if(1==f.S)break;g=h=n.substr(r,k);f=f.A;for(l=0;l<f.length;l+=2)if(h=h.replace(f[l],f[l+1]),g!=h){if(0==arguments[3])return g;break}n=n.substr(0,r)+h+n.substr(r+k,n.length);break}b+=n+v}return b};
window.mti_SR=function(a,c,b,e,d){a=a.replace(/(\r\n|\n|\r)/g,"");for(var f=a.split(/<[\/]?\s*\w.*?>/g),h="",g="",k=0;k<f.length;k++){var g=a.search(/<[\/]?\s*\w.*?>/g),l="";-1!=g&&(l=a.substring(g,a.indexOf(">")+1));a=a.substring(a.indexOf(">")+1);for(var m=f[k],g="",q=0;q<m.length;q++){for(var r=!1,u=b;0<u;u--){for(var v="",n=0;n<u;n++)"undefined"!=typeof m[q+n]&&(v+=mti_decimalToHex(m[q+n].charCodeAt(0),4).toUpperCase());if("undefined"!=typeof c["r"+v]){g="undefined"!=typeof c["r"+v]["o"+e]?g+
c["r"+v]["o"+e]:"undefined"!=typeof c["r"+v].o1?g+m[q]:g+c["r"+v];if(0==d)return g;r=!0;q+=u-1;break}}0==r&&(g+=m[q])}h+=g+l}return h};window.mti_R=function(a){return-1!=a.indexOf("(")||-1!=a.indexOf(")")||-1!=a.indexOf("*")||-1!=a.indexOf("+")||-1!=a.indexOf("?")||-1!=a.indexOf("{")||-1!=a.indexOf("}")||-1!=a.indexOf("\\")||-1!=a.indexOf("^")||-1!=a.indexOf("$")||-1!=a.indexOf(".")||-1!=a.indexOf("[")||-1!=a.indexOf("]")||-1!=a.indexOf("|")?new RegExp("\\"+a,""):new RegExp(a,"")};
window.mti_K=function(a,c,b,e,d,f,h,g){var k=0,l="",m="";a=a.replace(/(\r\n|\n|\r)/g,"");var q=a.split(/<[\/]?\s*\w.*?>/g),r=0,u=0,v=0,n;"undefined"!=typeof Userkernstring&&(n=Userkernstring.split(","));if(null==h){h=Array(d.length);for(var p=0;p<h.length;p++)h[p]=0}if(null==g)for(g=Array(d.length),p=0;p<g.length;p++)g[p]=0;if("string"==typeof b)for(k=b,b=Array(d.length),p=0;p<b.length;p++)b[p]=k;for(p=0;p<q.length;p++){k=a.search(/<[\/]?\s*\w.*?>/g);h="";g=0;-1!=k&&(h=a.substring(k,a.indexOf(">")+
1),a=a.substring(a.indexOf(">")+1));var w=0;v<r&&(v=r);for(var t=0;t<q[p].length;t++){var y=v+t;-1!=b[y].indexOf("px")?(k=parseInt(b[y].replace("px","")),l="px"):-1!=b[y].indexOf("em")?(k=parseInt(b[y].replace("em","")),l=2==f?"px":"em"):k=1;1==f&&(g=d[r]*k/c);w+=g;2==f?void 0!=n&&(k=0,"undefined"!=typeof n[y]&&(k=1==isNaN(parseFloat(n[y]))?0:parseFloat(n[y]).toFixed(1)),Math.abs(k)>Math.abs(w)?(u=1,m+='<span data-mti-otf = "mti-otf" style="letter-spacing:'+n[y]+l+';">'+q[p][t]+"</span>",w=0):.5>
Math.abs(g)&&.5>Math.abs(w)&&(m+=q[p][t])):.5>Math.abs(w)?m+=q[p][t]:(0==e?(u=1,m+='<span data-mti-otf = "mti-otf" style="letter-spacing:'+Math.round(w)+l+';" >'+q[p][t]+"</span>"):(u=1,m+='<span data-mti-otf = "mti-otf" style="letter-spacing:'+Math.round(w)+l+';">'+q[p][t]+"</span>"),w=0);r++}m+=h}return[m,u]};window.mti_HashTable=function(){var a={};this.ea=function(c,b){a[c]=b};this.Da=function(c){return a[c]}};
window.mti_KernArr=function(a,c){for(var b=c.replace(/(\r\n|\n|\r)/g,"").split(/<[\/]?\s*\w.*?>/g),e="",d=0;d<b.length;d++)e+=b[d];for(b=0;b<e.length;b++)a[b]=0};
window.mti_CRGPOS=function(a,c,b){var e=a.replace(/(\r\n|\n|\r)/g,""),d=e.split(/<[\/]?\s*\w.*?>/g),f;a=[];var h="",g=new mti_HashTable,e=new mti_HashTable;for(f=0;f<d.length;f++)h+=d[f];for(d=0;d<h.length;d++)f=e.Da(h.charCodeAt(d)),"undefined"!=typeof f?a[d]=f:(f=mti_decimalToHex(h.charCodeAt(d),4).toUpperCase(),a[d]=f,e.ea(h.charCodeAt(d),f));for(d=0;d<h.length;d++)e=a[d]+a[d+1],f=g.Da(e),"undefined"!=typeof f?b[d]+=f:"undefined"!=typeof c["r"+e]?"undefined"==typeof c["r"+e].o1?(b[d]+=c["r"+e],
g.ea(e,c["r"+e])):(b[d]+=c["r"+e].o1,b[d-1]+=c["r"+e].o2,g.ea(e,c["r"+e].o1)):"undefined"!=typeof c["u"+a[d]]&&(f=c["R"+c["u"+a[d]]],f=f["u"+a[d+1]],"undefined"!=typeof f?(g.ea(e,f),b[d]+=f):g.ea(e,0));return b};window.mti_decimalToHex=function(a,c){var b=Number(a).toString(16);if("undefined"!=typeof c)for(;b.length<c;)b="0"+b;return b};
})(this,document);